---
- hosts: localhost
  become: yes
  connection: local
  vars:
    - ag: /usr/bin/ansible-galaxy
  pre_tasks:
    - name: Check Ansible version > 2.10
      fail: msg="Ansible version should be >= 2.10 to run this playbook, current version is {{ansible_version.string}}"
      when: ansible_version.minor < 10
    - name: Check if ansible-galaxy collections are installed
      shell: "{{ag}} collection list | grep geerlingguy"
      register: result
      ignore_errors: true
    - name: Install Galaxy collections
      shell: "{{ag}} install -p roles/ {{item}}"
      with_items:
        - geerlingguy.apache
        - geerlingguy.mysql
        - geerlingguy.php
      when: result.rc != 0
  tasks:
    - name: Install mysql
      include_role:
        name: geerlingguy.mysql
    - name: Install apache
      include_role:
        name: geerlingguy.apache
    - name: Install php
      include_role:
        name: geerlingguy.php
