#####################
# Verify LAMP SEtup #
#####################
---
- hosts: demo
  become: yes
  tasks:
  - name: Include variables from lamp role
    include_vars: 
      file: roles/lamp/vars/main.yml
  - name: Check if port 80 is listening
    wait_for:
      port: 80
      timeout: 10
      msg: "Timeout waiting for 80 to respond"
    register: port_check
    ignore_errors: yes

  - name: Print message if Apache is not running
    debug:
       msg: "Apache not running"
    when: port_check.failed == true

  - name: Create a test database
    mysql_db:
      name: testdb
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: Gather the rpm package facts
    package_facts:
      manager: auto

  - name: Print if PHP doesnt exists
    debug: 
      msg: "PHP not found"
    when: "'php-mysql' not in ansible_facts.packages"


