---
- hosts: node01
  become: yes
  tasks:
    - name: Apt Update repositories cache
      apt:
        update_cache: yes

    - name: Install docker.io
      package: name=docker.io state=present

    - name: Start docker service
      service: name=docker state=started

    - name: Add user to docker group
      user: name=ubuntu group=docker state=present
      register: userDetails

    - debug: var=userDetails.group

    - name: Get Docker info
      block:
        - name: Get Docker info as ubuntu
          command: docker info
          register: output
        - debug: var=output.stdout
        - debug: var=output.rc
      become_user: ubuntu