---
- hosts: demo
  become: yes
  tasks:
    - name: Install apache
      package: name=apache2 state=present
      notify: handler2
    - name: Start Apache
      service: name=apache2 state=started
      notify: Restart Server
  handlers:
    - name: Restart Server
      command: echo "reboot"
    - name: handler2
      command: echo "reboot -2--"