---
- hosts: node01
  gather_facts: false
  vars:
    - state: present
  tasks:
    - name: Print message
      debug:
        msg: "The item is {{ item }}"
        loop:
          - hello
          - World
          - from
          - Sara
        loop_control:
          pause: 5